# -*- coding: utf-8 -*-
"""Calculando Médias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pBPTllaxQOLdLeSu3IK28atJcyaw3cYr
"""

nota1 = float(input("Digite a nota 1: "))
nota2 = float(input("Digite a nota 2: "))
nota3 = float(input("Digite a nota 3: "))
nota4 = float(input("Digite a nota 4: "))

media = (nota1 + nota2 + nota3 + nota4)/4

print("\nSua média aritimética é: " + str(media))

if media <= 7:
    print("\nAluno reprovado!")
else:
    print("\nParabéns Aluno aprovado!")